# Problem 12 Highly divisible triangular number

# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

sayi = 1
artis = 1

def carpanSayisi(sayi):
  i = 2
  x = 0
  toplam = 1
  dizi = []
  while(sayi != 1):
    if(sayi % i == 0):
      sayi = sayi / i
      x += 1
    else:
      if(x != 0):
        dizi.append(x + 1)
      x = 0
      i += 1
  dizi.append(x + 1)
  for j in dizi:
    toplam = toplam * j
  return toplam

while True:
  carpan = carpanSayisi(sayi)
  if(carpan >= 481):
    break
  artis += 1
  sayi += artis
  
print(sayi)
